package db

const createGVTable = `CREATE TABLE GEO_VELOCITY_EVENTS (
    ID         INTEGER       PRIMARY KEY AUTOINCREMENT
                             NOT NULL,
    UUID       BLOB (16)     UNIQUE
                             NOT NULL,
    LOGIN_TIME BIGINT (10)   NOT NULL,
    USERNAME   VARCHAR (255) NOT NULL,
    CREATED    DATETIME      DEFAULT (CURRENT_TIMESTAMP),
    IP_ADDRESS TEXT          NOT NULL,
    LAT        DECIMAL       NOT NULL,
    LONG       DECIMAL       NOT NULL,
    RADIUS     INTEGER (3)   NOT NULL
);
`

const InsertGVTable = `INSERT INTO GEO_VELOCITY_EVENTS (UUID,LOGIN_TIME,USERNAME,IP_ADDRESS,LAT,LONG,RADIUS) VALUES (?,?,?,?,?,?,?);`
const UUIDExist = `SELECT ID FROM GEO_VELOCITY_EVENTS WHERE UUID=?`
const UserLoginTimeExists = `SELECT ID FROM GEO_VELOCITY_EVENTS WHERE LOGIN_TIME=? AND USERNAME=?`
const GetSubsequent = `select IP_ADDRESS,LAT,LONG,RADIUS,LOGIN_TIME from GEO_VELOCITY_EVENTS WHERE LOGIN_TIME > ? ORDER BY LOGIN_TIME ASC LIMIT 1`
const GetPrevious = `select IP_ADDRESS,LAT,LONG,RADIUS,LOGIN_TIME from GEO_VELOCITY_EVENTS WHERE LOGIN_TIME < ? ORDER BY LOGIN_TIME DESC LIMIT 1`
